
const dk = new Intl.NumberFormat('da-DK');
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const median=a=>{if(!a.length)return null;let s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const fmtMin=v=>v==null?'–':`${Math.round(v)} min.`;
const byCount=(arr,key)=>arr.reduce((m,r)=>{let k=key(r)||'Ukendt';m[k]=(m[k]||0)+1;return m},{});
const sortedEntries=o=>Object.entries(o).sort((a,b)=>b[1]-a[1] || a[0].localeCompare(b[0],'da'));
const monthName=m=>{ if(!m) return '–'; const [y,mo]=m.split('-'); return `${mo}/${y}`; };
function renderChart(charts,id,type,entries,label,opts={}){const ctx=document.getElementById(id);if(!ctx)return;if(charts[id])charts[id].destroy();charts[id]=new Chart(ctx,{type,data:{labels:entries.map(e=>e[0]),datasets:[{label,data:entries.map(e=>e[1]),tension:.25}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'||opts.legend}},scales:type==='doughnut'?{}:{y:{beginAtZero:true,ticks:{precision:0}}}}});}
function fillSelect(id,values,label='Alle'){const el=document.getElementById(id);el.innerHTML=`<option value="">${label}</option>`+[...values].filter(Boolean).sort().map(v=>`<option>${v}</option>`).join('');}
function getFilters(){return {y:document.getElementById('yearFilter')?.value||'',qt:document.getElementById('quarterFilter')?.value||'',from:document.getElementById('dateFrom')?.value||'',to:document.getElementById('dateTo')?.value||'',st:document.getElementById('stationFilter')?.value||'',ca:document.getElementById('causeFilter')?.value||'',q:(document.getElementById('searchBox')?.value||'').toLowerCase()};}
function recordQuarter(r){const m=parseInt((r.month||r.date||'').slice(5,7),10);return Math.ceil(m/3);}
function applyFilterTo(raw){const {y,qt,from,to,st,ca,q}=getFilters();return raw.filter(r=>(!y||String(r.year)===y)&&(!qt||String(recordQuarter(r))===qt)&&(!from||(r.date||'')>=from)&&(!to||(r.date||'')<=to)&&(!st||r.station===st)&&(!ca||r.cause===ca)&&(!q||(`${r.date} ${r.month} ${r.station} ${r.cause} ${r.vagtcentral||''} ${r.category||''} ${r.title||''}`).toLowerCase().includes(q)));}
function setupFilterControls(raw, onChange){fillSelect('yearFilter',new Set(raw.map(r=>r.year)),'Alle år');fillSelect('stationFilter',new Set(raw.map(r=>r.station)),'Alle stationer');fillSelect('causeFilter',new Set(raw.map(r=>r.cause)),'Alle årsager');['yearFilter','quarterFilter','dateFrom','dateTo','stationFilter','causeFilter','searchBox'].forEach(id=>{const el=document.getElementById(id); if(el) el.oninput=onChange; if(el) el.onchange=onChange;});document.getElementById('resetBtn').onclick=()=>{['yearFilter','quarterFilter','dateFrom','dateTo','stationFilter','causeFilter','searchBox'].forEach(id=>{const el=document.getElementById(id); if(el) el.value='';});onChange();};}
function validGeo(records){return records.filter(r=>Number(r.lat)&&Number(r.lon)).sort((a,b)=>(a.date||'').localeCompare(b.date||''));}
function dayNight(r){const h=parseInt((r.alarm_time||'12:00').slice(0,2),10); if(Number.isNaN(h)) return 'ukendt'; return (h>=22||h<6)?'nat':'dag';}
function weatherLabel(r){return 'Vejrdata ikke koblet på endnu';}

let raw=[],filtered=[],charts={},map,markers=[],boatMarker=null,playTimer=null,currentStep=0;
async function init(){const res=await fetch('assets/assistancer-public.json');raw=(await res.json()).records;setupFilterControls(raw,applyFilters);setupMap();document.getElementById('playBtn').onclick=togglePlay;document.getElementById('timeline').oninput=e=>{currentStep=+e.target.value;renderTimeline();};document.getElementById('exportBtn').onclick=()=>window.print();applyFilters();}
function applyFilters(){filtered=applyFilterTo(raw);updateDashboard();resetTimeline();}
function updateDashboard(){document.getElementById('kpiAssists').textContent=dk.format(filtered.length);document.getElementById('kpiPersons').textContent=dk.format(filtered.reduce((s,r)=>s+(r.persons||0),0));let causes=sortedEntries(byCount(filtered,r=>r.cause));document.getElementById('kpiTopCause').textContent=causes[0]?.[0]||'–';let months=sortedEntries(byCount(filtered,r=>r.month));document.getElementById('kpiTopMonth').textContent=monthName(months[0]?.[0]);const monthEntries=Object.entries(byCount(filtered,r=>r.month)).sort().map(([k,v])=>[monthName(k),v]);renderChart(charts,'monthlyChart','bar',monthEntries,'Assistancer');renderChart(charts,'causeChart','doughnut',causes.slice(0,9),'Årsager');document.querySelector('#pressTable tbody').innerHTML=Object.entries(byCount(filtered,r=>`${r.month}|${r.cause}`)).sort().map(([k,v])=>{const [m,c]=k.split('|');return `<tr><td>${monthName(m)}</td><td>${c}</td><td>${dk.format(v)}</td></tr>`}).join('')||'<tr><td colspan="3">Ingen data i det valgte filter.</td></tr>';}
function setupMap(){map=L.map('map').setView([56.05,10.8],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);}
function resetTimeline(){const valid=validGeo(filtered);document.getElementById('timeline').max=Math.max(0,valid.length-1);currentStep=valid.length?valid.length-1:0;document.getElementById('timeline').value=currentStep;renderTimeline();}
function renderTimeline(){markers.forEach(m=>map.removeLayer(m));markers=[];if(boatMarker){map.removeLayer(boatMarker);boatMarker=null;}const valid=validGeo(filtered);const shown=valid.slice(0,currentStep+1);shown.forEach((r,i)=>{const marker=L.circleMarker([r.lat,r.lon],{radius:i===shown.length-1?9:5,weight:2,fillOpacity:.65}).bindPopup(`<strong>${r.date}</strong><br>${r.station}<br>${r.cause}<br>${r.persons??'–'} personer ombord<br>${weatherLabel(r)}`);marker.addTo(map);markers.push(marker);});const overlay=document.getElementById('nightOverlay');if(shown.length){let last=shown[shown.length-1];document.getElementById('timelineLabel').textContent=`Viser ${shown.length} af ${valid.length} – seneste punkt: ${last.date}, ${last.station}, ${last.cause}`;document.getElementById('weatherBadge').textContent=`${dayNight(last)==='nat'?'🌙 Nat':'☀️ Dag'} · ${weatherLabel(last)}`;overlay.style.opacity=dayNight(last)==='nat'?1:0;boatMarker=L.marker([last.lat,last.lon],{icon:L.divIcon({className:'boatIcon',html:'🚤',iconSize:[24,24]})}).addTo(map);}else{document.getElementById('timelineLabel').textContent='Ingen punkter i dette filter.';document.getElementById('weatherBadge').textContent='Vejrdata ikke koblet på endnu';overlay.style.opacity=0;}}
function togglePlay(){const btn=document.getElementById('playBtn');if(playTimer){clearInterval(playTimer);playTimer=null;btn.textContent='▶ Afspil';return;}currentStep=0;document.getElementById('timeline').value=0;btn.textContent='⏸ Pause';playTimer=setInterval(()=>{const max=+document.getElementById('timeline').max;if(currentStep>=max){togglePlay();return;}currentStep++;document.getElementById('timeline').value=currentStep;renderTimeline();},+document.getElementById('speedRange').value);}
init();
